services:


  chainlit-app-frlp:
    container_name: chainlit-frlp
    build:
      context: chainlit_app/
      dockerfile: Dockerfile
    ports:
      - 8003:80
    environment:
      - MODEL_URL=http://ollama
      - MODEL_PORT=11434
      - DB_URL=http://vector-db
      - DB_PORT=8006
      - LLAMA_PARSE_API_KEY=${LLAMA_PARSE_API_KEY}
      - USERS_API_URL=http://users_db
      - USERS_API_PORT=8009
      - LITERAL_API_KEY=${LITERAL_API_KEY}
      - CHAINLIT_AUTH_SECRET=${CHAINLIT_AUTH_SECRET}
      - OAUTH_GOOGLE_CLIENT_ID=${OAUTH_GOOGLE_CLIENT_ID}
      - OAUTH_GOOGLE_CLIENT_SECRET=${OAUTH_GOOGLE_CLIENT_SECRET}
      - USE_AIM=false
    restart: ${RESTART_POLICY:-no}


networks:
  default:
    name: lines-network
    external: true