services:

  ollama:
    container_name: ollama
    image: ollama/ollama:0.6.5
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_DEBUG=true
      - CUDA_VISIBLE_DEVICES=0
      - OLLAMA_CONTEXT_LENGTH=8192
    entrypoint: bash -c "ollama serve & pid=$!; sleep 5; ollama pull llama3.1; ollama pull gemma3:1b; ollama pull granite-embedding:278m; wait $pid"
    restart: ${RESTART_POLICY:-no}

    labels:
      - "traefik.enable=true"
      - "traefik.http.services.ollama.loadbalancer.server.port=11434"
      - "traefik.http.routers.ollama-http.rule=PathRegexp(`^/(api|v1).*`)" # Route user requests matching /api or /v1
      - "traefik.http.services.ollama.loadbalancer.passhostheader=false"

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  
  aim-server:
    image: aimstack/aim:3.28.0
    command: server --host 0.0.0.0
    container_name: aim_server
    environment:
        - AIM_UI_TELEMETRY_ENABLED=0
    ports:
        - 53800:53800 
    volumes:
        - aim-volume:/opt/aim
    restart: ${RESTART_POLICY:-no}

  aim-ui:
    image: aimstack/aim:3.28.0
    command: up --host 0.0.0.0
    container_name: aim_ui
    environment:
        - AIM_UI_TELEMETRY_ENABLED=0
    ports:
        - 43800:43800
    volumes:
        - aim-volume:/opt/aim
    restart: ${RESTART_POLICY:-no}

  chainlit-app:
    container_name: prod-chainlit
    build:
      context: chainlit_app/
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - MODEL_URL=http://ollama
      - MODEL_PORT=11434
      - DB_URL=http://vector-db
      - DB_PORT=8006
      - LLAMA_PARSE_API_KEY=${LLAMA_PARSE_API_KEY}
      - USERS_API_URL=http://users_db
      - USERS_API_PORT=8009
      - LITERAL_API_KEY=${LITERAL_API_KEY}
      - CHAINLIT_AUTH_SECRET=${CHAINLIT_AUTH_SECRET}
      - OAUTH_GOOGLE_CLIENT_ID=${OAUTH_GOOGLE_CLIENT_ID}
      - OAUTH_GOOGLE_CLIENT_SECRET=${OAUTH_GOOGLE_CLIENT_SECRET}
      - USE_AIM=true
    volumes:
      - rag-volume:/chainlit_app/database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chainlit-router.entrypoints=web"
      - "traefik.http.routers.chainlit-router.rule=PathPrefix(`/`)"
      - "traefik.http.services.chainlit-router.loadbalancer.server.port=80"
    depends_on:
      - aim-server
    restart: ${RESTART_POLICY:-no}

  traefik:
    image: traefik:v3.3
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8000"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      # - "traefik.http.routers.traefik.middlewares=auth"
      # - "traefik.http.middlewares.auth.basicauth.users=myuser:$$apr1$$HtC6EB1y$$Xn8dAvzj5l2FGFXlrT2Rl1"
    restart: ${RESTART_POLICY:-no}

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: usuarios_db
    volumes:
      - ./volumes/mysql_data/users:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$MYSQL_ROOT_PASSWORD || exit 1"]
    restart: ${RESTART_POLICY:-no}

  users_db:
    build:
      context: users/
      dockerfile: Dockerfile
    container_name: users_db
    depends_on:
      mysql_db:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql+pymysql://root:password@mysql_db:3306/usuarios_db
    ports:
      - "8009:8009"
    restart: ${RESTART_POLICY:-no}

networks:
  default:
    name: lines-network

volumes:
  ollama:
    name: ollama
  rag-volume:
    driver: local
  aim-volume:
    driver: local
