include:
  - compose.base.yml

services:
  vector-db:
    image: chroma
    container_name: db-chroma
    build:
      context: vectordbs/Chroma
      dockerfile: Dockerfile
    ports:
      - 8006:8006
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/chroma:/code/database/
    restart: ${RESTART_POLICY:-no}
